---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: personas-django-pvc
  namespace: calvarado2004
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: personas-django-credentials
  namespace: calvarado2004
type: Opaque
data:
  user: UG9zdGdyZXM=
  password: UG9zdGdyZXNrOHMk 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas-django-db-deployment
  namespace: calvarado2004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas-django-db-container
  template:
    metadata:
      labels:
        app: personas-django-db-container
        tier: backend
    spec:
      containers:
        - name: personas-django-db-container
          image: postgres:12.4
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: personas-django-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: personas-django-credentials
                  key: password

            - name: POSTGRES_DB
              value: kubernetes_django

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: "/var/lib/postgresql/data"

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: personas-django-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: personas-django-db-service
  namespace: calvarado2004
spec:
  selector:
    app: personas-django-db-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas-django-deployment
  namespace: calvarado2004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas-django-container
  template:
    metadata:
      labels:
        app: personas-django-container
    spec:
      containers:
        - name: django
          image: calvarado2004/django-personas:1.0.2
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: personas-django-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: personas-django-credentials
                  key: password

            - name: POSTGRES_HOST
              value: personas-django-db-service

      initContainers:
        - name: django-init
          image: calvarado2004/django-personas:1.0.2
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: personas-django-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: personas-django-credentials
                  key: password

            - name: POSTGRES_HOST
              value: personas-django-db-service
---
kind: Service
apiVersion: v1
metadata:
  name: personas-django-service
  namespace: calvarado2004
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: personas-django-container
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

